## PyTorch库的使用

### 标量对向量求导

In [1]:
import torch
x=torch.arange(4.0)#生成一个长度为4的张量
x

tensor([0., 1., 2., 3.])

In [2]:
x.requires_grad=True
x.grad

In [3]:
y=torch.dot(x,x)
y

tensor(14., grad_fn=<DotBackward0>)

In [4]:
y.backward()
x.grad

tensor([0., 2., 4., 6.])

In [5]:
#默认情况下torch会自动累计grad，因此要执行清空操作
x.grad.zero_()
y=x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

### 向量对向量的求导（深度学习不常用）

In [6]:
x.grad.zero_()
y=x*x
y.sum().backward()
x.grad

tensor([0., 2., 4., 6.])

In [7]:
x.grad.zero_()
y=x*x
u=y.detach()#之前的y=x*x，detach()后y=x*x具体的张量，不再是一个关于x的表达式
z=u*x
z.sum().backward()
x.grad

tensor([0., 1., 4., 9.])

### PyTorch库中的一些函数的用法

In [8]:
x=torch.normal(mean=0,std=1,size=(5,5))#生成一个五行五列的以0为均值，1为标准差的张量
x

tensor([[-0.2462, -1.4928,  0.5101,  1.6421,  0.3255],
        [-0.9024, -0.6835, -0.0339, -0.6578, -1.2534],
        [-1.0293,  1.3824,  0.6016, -0.2069, -1.6440],
        [-0.3677, -0.0536,  1.3980,  0.2279,  0.8445],
        [-0.2198, -0.0511,  0.1358, -0.3237,  0.7491]])

In [9]:
w=torch.normal(0,1,(5,1))
b=1
y=torch.matmul(x,w)+b#矩阵乘法
y
y=x@w
y

tensor([[ 3.2837],
        [-2.3813],
        [-3.5758],
        [ 2.7522],
        [ 1.4940]])

In [10]:
print(y.reshape(-1,1))#重构为一列
print(y.reshape(1,-1))#重构为一行
print(len(y.reshape(-1,1)))
print(len(y.reshape(1,-1)))

tensor([[ 3.2837],
        [-2.3813],
        [-3.5758],
        [ 2.7522],
        [ 1.4940]])
tensor([[ 3.2837, -2.3813, -3.5758,  2.7522,  1.4940]])
5
1


In [11]:
a=torch.tensor([[1,2,3],[4,5,6]])
print(a.sum(0,keepdim=True))
print(a.sum(1,keepdim=True))

tensor([[5, 7, 9]])
tensor([[ 6],
        [15]])


In [12]:
a=torch.tensor([[1,2,3],[4,5,6]])
print(torch.matmul(a,a.T))#做常规的矩阵乘法

tensor([[14, 32],
        [32, 77]])


In [13]:
W=torch.normal(0,0.01,size=(784,10),requires_grad=True)
print(W.shape)
print(W.shape[0])#返回的是第0维的shape

torch.Size([784, 10])
784


In [14]:
a=torch.tensor([[1,2,3],
                [3,7,1],
                [2,1,3]])
print(a.argmax(axis=1))
print(a.argmax(axis=0))

tensor([2, 1, 2])
tensor([1, 1, 0])


In [15]:
a=torch.tensor([[1,-2,3],
                [-4,5,6]])
print(torch.zeros_like(a))
print(torch.max(a,torch.zeros_like(a)))

tensor([[0, 0, 0],
        [0, 0, 0]])
tensor([[1, 0, 3],
        [0, 5, 6]])


In [16]:
import numpy as np
import torch
true_w = np.zeros(20)  # 分配大量的空间
true_w[0:4] = np.array([5, 1.2, -3.4, 5.6])
features = np.random.normal(size=(100 + 100, 1))
np.random.shuffle(features)
poly_features = np.power(features, np.arange(20).reshape(1, -1))#扩展为features行，20列数组
labels = np.dot(poly_features, true_w)
print(np.dot(poly_features, true_w).shape)

(200,)


In [17]:
a=torch.tensor([[1,2,3],
                [4,5,6]])
b=torch.tensor([[4,5,6],
               [7,8,9]])
print(torch.cat((a,b),1))
print(torch.cat((a,b),0))

tensor([[1, 2, 3, 4, 5, 6],
        [4, 5, 6, 7, 8, 9]])
tensor([[1, 2, 3],
        [4, 5, 6],
        [4, 5, 6],
        [7, 8, 9]])


In [18]:
import torch
x = torch.tensor([[1,2,3.2],
                  [2,4,5]])
print(x.mean(dim=0))
print(x.mean(dim=1))
print(x.mean(dim=0, keepdim=True))
print(x.mean(dim=1, keepdim=True))

tensor([1.5000, 3.0000, 4.1000])
tensor([2.0667, 3.6667])
tensor([[1.5000, 3.0000, 4.1000]])
tensor([[2.0667],
        [3.6667]])


In [19]:
x = torch.randn(size=(2,3,4))
print(x)
print(x.mean(dim=(0,2), keepdim=True)) # 那个维度不在求均值的dim中，就保留那个维度的特征

tensor([[[ 0.4858, -0.3406, -0.8538,  0.4474],
         [-1.2426, -0.7101,  0.4600,  0.3135],
         [ 1.7279,  0.6891, -1.2396, -1.3178]],

        [[ 1.9972,  0.9521, -2.4685,  1.7285],
         [-0.0884,  0.0291,  0.0431,  0.1294],
         [-0.8150, -0.1808,  0.7928,  1.0895]]])
tensor([[[ 0.2435],
         [-0.1333],
         [ 0.0932]]])


In [20]:
from torch import meshgrid
import torch

a = torch.tensor([1, 2, 3])
b = torch.tensor([2, 3, 4])
print(meshgrid([a, b]))
b = torch.tensor([2, 3])
x, y =meshgrid([a, b])
print(x, y)
print(x.reshape(-1), y.reshape(-1))

(tensor([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]]), tensor([[2, 3, 4],
        [2, 3, 4],
        [2, 3, 4]]))
tensor([[1, 1],
        [2, 2],
        [3, 3]]) tensor([[2, 3],
        [2, 3],
        [2, 3]])
tensor([1, 1, 2, 2, 3, 3]) tensor([2, 3, 2, 3, 2, 3])


C:\Users\33143\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ..\aten\src\ATen\native\TensorShape.cpp:3484.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]


In [21]:
from torch import repeat_interleave
import torch
a = torch.tensor([[1, 2], [3, 4]])
print(repeat_interleave(a, 2, dim=0))
print(repeat_interleave(a, 4, dim=1))
print(a.repeat(3, 1))

tensor([[1, 2],
        [1, 2],
        [3, 4],
        [3, 4]])
tensor([[1, 1, 1, 1, 2, 2, 2, 2],
        [3, 3, 3, 3, 4, 4, 4, 4]])
tensor([[1, 2],
        [3, 4],
        [1, 2],
        [3, 4],
        [1, 2],
        [3, 4]])


In [22]:
from torch import stack
a = torch.tensor([1, 2, 3])
b = torch.tensor([3, 4, 5])
print(stack((a, b)))
print(stack((a, b)).T)
print(stack((a, b), dim=1))

tensor([[1, 2, 3],
        [3, 4, 5]])
tensor([[1, 3],
        [2, 4],
        [3, 5]])
tensor([[1, 3],
        [2, 4],
        [3, 5]])


In [23]:
import torch
a = torch.tensor([[1, 2, 3],
                 [4, 5, 6]])
b = torch.tensor([[2, 2, 3],
                  [4, 3, 6]])
c = torch.tensor([2, 1 ,0])

print(torch.max(a, b))
print(torch.max(a[:, None, :], c))
print(torch.max(a, dim=0))

tensor([[2, 2, 3],
        [4, 5, 6]])
tensor([[[2, 2, 3]],

        [[4, 5, 6]]])
torch.return_types.max(
values=tensor([4, 5, 6]),
indices=tensor([1, 1, 1]))


In [24]:
import torch
a = torch.tensor([1, 2, 3, 4])
b = torch.tensor([3, 3, 1, 2])
print((a - b).clamp(min=0))

tensor([0, 0, 2, 2])


In [25]:
import torch
print(torch.tensor([1, -1 , 2, 0]))
print(torch.tensor([1, -1 , 2, 0]).unsqueeze(-1))
print(torch.tensor([1, -1 , 2, 0]).unsqueeze(-1).repeat(1, 4))

tensor([ 1, -1,  2,  0])
tensor([[ 1],
        [-1],
        [ 2],
        [ 0]])
tensor([[ 1,  1,  1,  1],
        [-1, -1, -1, -1],
        [ 2,  2,  2,  2],
        [ 0,  0,  0,  0]])


In [33]:
import torch
a = torch.tensor([[1, 2, 3],
                  [0, -1, -2]])
print(torch.nonzero(a))
print(torch.nonzero(a >= 0))

tensor([[0, 0],
        [0, 1],
        [0, 2],
        [1, 1],
        [1, 2]])
tensor([[0, 0],
        [0, 1],
        [0, 2],
        [1, 0]])


In [ ]:
torch.tensor([[0] * 4,
             [0.9, 0.8, 0.7, 0.1],
             [0.1, 0.2, 0.3, 0.9]])