## PyTorch库的使用

### 标量对向量求导

In [1]:
import torch
x=torch.arange(4.0)#生成一个长度为4的张量
x

tensor([0., 1., 2., 3.])

In [2]:
x.requires_grad=True
x.grad

In [3]:
y=torch.dot(x,x)
y

tensor(14., grad_fn=<DotBackward0>)

In [4]:
y.backward()
x.grad

tensor([0., 2., 4., 6.])

In [5]:
#默认情况下torch会自动累计grad，因此要执行清空操作
x.grad.zero_()
y=x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

### 向量对向量的求导（深度学习不常用）

In [6]:
x.grad.zero_()
y=x*x
y.sum().backward()
x.grad

tensor([0., 2., 4., 6.])

In [7]:
x.grad.zero_()
y=x*x
u=y.detach()#之前的y=x*x，detach()后y=x*x具体的张量，不再是一个关于x的表达式
z=u*x
z.sum().backward()
x.grad

tensor([0., 1., 4., 9.])

### PyTorch库中的一些函数的用法

In [17]:
x=torch.normal(mean=0,std=1,size=(5,5))#生成一个五行五列的以0为均值，1为标准差的张量
x

tensor([[-1.1035, -0.1544,  0.1072,  0.1773, -0.5543],
        [ 0.6013, -0.9951,  0.1199, -0.5381, -1.7457],
        [ 1.4763, -1.0639,  0.4542,  1.0019, -1.1304],
        [ 0.2685, -0.5803, -1.2030,  0.0497,  0.9629],
        [-0.0969,  0.1444,  0.5901, -2.4575,  0.6635]])

In [22]:
w=torch.normal(0,1,(5,1))
b=1
y=torch.matmul(x,w)+b#矩阵乘法
y
y=x@w
y

tensor([[ 1.1375],
        [-0.1369],
        [-3.5271],
        [-0.4638],
        [ 1.3484]])

In [10]:
print(y.reshape(-1,1))#重构为一列
print(y.reshape(1,-1))#重构为一行
print(len(y.reshape(-1,1)))
print(len(y.reshape(1,-1)))

tensor([[ 3.9682],
        [ 2.8297],
        [ 1.5248],
        [-4.2307],
        [-0.3626]])
tensor([[ 3.9682,  2.8297,  1.5248, -4.2307, -0.3626]])
5
1


In [11]:
a=torch.tensor([[1,2,3],[4,5,6]])
print(a.sum(0,keepdim=True))
print(a.sum(1,keepdim=True))

tensor([[5, 7, 9]])
tensor([[ 6],
        [15]])


In [12]:
a=torch.tensor([[1,2,3],[4,5,6]])
print(torch.matmul(a,a.T))#做常规的矩阵乘法

tensor([[14, 32],
        [32, 77]])


In [13]:
W=torch.normal(0,0.01,size=(784,10),requires_grad=True)
print(W.shape)
print(W.shape[0])#返回的是第0维的shape

torch.Size([784, 10])
784


In [14]:
a=torch.tensor([[1,2,3],
                [3,7,1],
                [2,1,3]])
print(a.argmax(axis=1))
print(a.argmax(axis=0))

tensor([2, 1, 2])
tensor([1, 1, 0])


In [16]:
a=torch.tensor([[1,-2,3],
                [-4,5,6]])
print(torch.zeros_like(a))
print(torch.max(a,torch.zeros_like(a)))

tensor([[0, 0, 0],
        [0, 0, 0]])
tensor([[1, 0, 3],
        [0, 5, 6]])
