## PyTorch库的使用

### 标量对向量求导

In [1]:
import torch
x=torch.arange(4.0)#生成一个长度为4的张量
x

tensor([0., 1., 2., 3.])

In [2]:
x.requires_grad=True
x.grad

In [3]:
y=torch.dot(x,x)
y

tensor(14., grad_fn=<DotBackward0>)

In [4]:
y.backward()
x.grad

tensor([0., 2., 4., 6.])

In [5]:
#默认情况下torch会自动累计grad，因此要执行清空操作
x.grad.zero_()
y=x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

### 向量对向量的求导（深度学习不常用）

In [6]:
x.grad.zero_()
y=x*x
y.sum().backward()
x.grad

tensor([0., 2., 4., 6.])

In [7]:
x.grad.zero_()
y=x*x
u=y.detach()#之前的y=x*x，detach()后y=x*x具体的张量，不再是一个关于x的表达式
z=u*x
z.sum().backward()
x.grad

tensor([0., 1., 4., 9.])

### PyTorch库中的一些函数的用法

In [8]:
x=torch.normal(mean=0,std=1,size=(5,5))#生成一个五行五列的以0为均值，1为标准差的张量
x

tensor([[-0.2689, -1.8256,  1.0693, -0.4972,  1.6370],
        [ 1.0294, -1.0751, -0.4302, -1.0435, -1.5749],
        [ 1.0391,  0.4227, -0.8637, -0.4223,  0.4614],
        [ 0.0410, -3.2144,  0.5378, -0.4582,  0.5829],
        [-0.7846,  0.0610,  0.4181, -1.0344, -1.5630]])

In [9]:
w=torch.normal(0,1,(5,1))
b=1
y=torch.matmul(x,w)+b#矩阵乘法
y

tensor([[4.5912],
        [4.3138],
        [0.9298],
        [6.6013],
        [2.2554]])

In [10]:
print(y.reshape(-1,1))#重构为一列
print(y.reshape(1,-1))#重构为一行
print(len(y.reshape(-1,1)))
print(len(y.reshape(1,-1)))

tensor([[4.5912],
        [4.3138],
        [0.9298],
        [6.6013],
        [2.2554]])
tensor([[4.5912, 4.3138, 0.9298, 6.6013, 2.2554]])
5
1


In [12]:
a=torch.tensor([[1,2,3],[4,5,6]])
print(a.sum(0,keepdim=True))
print(a.sum(1,keepdim=True))

tensor([[5, 7, 9]])
tensor([[ 6],
        [15]])


In [15]:
a=torch.tensor([[1,2,3],[4,5,6]])
print(torch.matmul(a,a.T))#做常规的矩阵乘法

tensor([[14, 32],
        [32, 77]])


In [16]:
W=torch.normal(0,0.01,size=(784,10),requires_grad=True)
print(W.shape)
print(W.shape[0])#返回的是第0维的shape

torch.Size([784, 10])
784


In [18]:
a=torch.tensor([[1,2,3],
                [3,7,1],
                [2,1,3]])
print(a.argmax(axis=1))
print(a.argmax(axis=0))

tensor([2, 1, 2])
tensor([1, 1, 0])
