# PyTorch Notes

## torch.stack
每个tensor的size必须相同，与torch.cat的区别在于，torch.stack形成了新的维度，而torch.cat不形成新的维度

In [9]:
import torch
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])
c = torch.stack([a, b], dim=0)
d = torch.stack([a, b], dim=1)
# e = torch.tensor([[1, 2, 3], [4, 5, 6]])
# f = torch.stack([a, e], dim=1) Error:stack expects each tensor to be equal size, but got [3] at entry 0 and [2, 3] at entry 1
print('dim=0 stack:', c)
print('dim=1 stack:', d)

dim=0 stack: tensor([[1, 2, 3],
        [4, 5, 6]])
dim=1 stack: tensor([[1, 4],
        [2, 5],
        [3, 6]])


## torch.cat
在相应dim上进行扩展，别的dim的个数不变

In [10]:
import torch
a = torch.tensor([[1, 2, 3], [1, 2, 3]])
b = torch.cat((a, a), dim=0)
c = torch.cat((a, a), dim=1)
print('dim=0 cat:', b)
print('dim=1 cat:', c)

dim=0 cat: tensor([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]])
dim=1 cat: tensor([[1, 2, 3, 1, 2, 3],
        [1, 2, 3, 1, 2, 3]])


## torch.split
torch.split(tensor, split_size_or_sections, dim=0)
torch.chunk是比较简单的split

In [11]:
import torch
a = torch.randn(size=(5, 2))
print('tensor:', a)
b = torch.split(a, 2) # 在dim=0上，每两个划一个tensor
c = torch.split(a, [1, 4]) # 在dim=0上，按[1, 4]划分tensor
print('b:', b)
print('c:', c)

tensor: tensor([[-0.9594, -0.7556],
        [-1.6402,  1.5177],
        [ 1.8255,  1.6826],
        [ 0.4145,  0.4089],
        [-0.4216,  0.1295]])
b: (tensor([[-0.9594, -0.7556],
        [-1.6402,  1.5177]]), tensor([[1.8255, 1.6826],
        [0.4145, 0.4089]]), tensor([[-0.4216,  0.1295]]))
c: (tensor([[-0.9594, -0.7556]]), tensor([[-1.6402,  1.5177],
        [ 1.8255,  1.6826],
        [ 0.4145,  0.4089],
        [-0.4216,  0.1295]]))


## torch.tensor.detach
在 PyTorch 中，.detach() 方法的主要作用是将一个变量从当前的计算图中分离出来，阻止未来的计算在这个变量上的操作被记录在图中。这意味着使用 .detach() 方法的变量不会在反向传播过程中更新其梯度

## torch.meshgrid
将一组横坐标和一组纵坐标扩展后得以两两组合，相当于笛卡尔积，一般会reshape，方便后续匹配x和y

In [12]:
import torch
a = torch.tensor([1, 2, 3, 4])
b = torch.tensor([1, 2, 3])
x, y = torch.meshgrid([a, b], indexing='ij')
print('x:', x)
print('y:', y)
print('x.reshape:', x.reshape(-1))
print('y.reshape:', y.reshape(-1))

x: tensor([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3],
        [4, 4, 4]])
y: tensor([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]])
x.reshape: tensor([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4])
y.reshape: tensor([1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])


## torch.tensor.repeat

In [13]:
import torch
a = torch.tensor([1, 2, 3])
x = 5  # 行上扩展的个数
y = 2  # 列上扩展的个数
b = a.repeat(x, y)
print('b:', b)

b: tensor([[1, 2, 3, 1, 2, 3],
        [1, 2, 3, 1, 2, 3],
        [1, 2, 3, 1, 2, 3],
        [1, 2, 3, 1, 2, 3],
        [1, 2, 3, 1, 2, 3]])


## torch.repeat_interleave 
交错的重复
similar to numpy.repeat

In [14]:
import torch
a = torch.tensor([1, 2, 3])
b = a.repeat_interleave(2)
c = torch.repeat_interleave(a, 2, dim=0)
d = torch.tensor([[1, 2], [3, 4]])
e = torch.repeat_interleave(d, 2, dim=0)
f = torch.repeat_interleave(d, 2, dim=1)
print('b:', b)
print('c:', c)
print('e:', e)
print('f:', f)

b: tensor([1, 1, 2, 2, 3, 3])
c: tensor([1, 1, 2, 2, 3, 3])
e: tensor([[1, 2],
        [1, 2],
        [3, 4],
        [3, 4]])
f: tensor([[1, 1, 2, 2],
        [3, 3, 4, 4]])


## torch.unsqueeze
返回的tensor指定的维度的size为1

In [15]:
import torch
a = torch.tensor([[1, 2, 3],[4, 5, 6]])
b = torch.unsqueeze(a, dim=0)
c = torch.unsqueeze(a, dim=1)
d = torch.unsqueeze(a, dim=2)
print('b:', b)
print('c:', c)
print('d:', d)

b: tensor([[[1, 2, 3],
         [4, 5, 6]]])
c: tensor([[[1, 2, 3]],

        [[4, 5, 6]]])
d: tensor([[[1],
         [2],
         [3]],

        [[4],
         [5],
         [6]]])


## torchvision.read_image
将图片通过RGB值读入变量

In [16]:
import torchvision
image = torchvision.io.read_image('./sample_path')

RuntimeError: [Errno 2] No such file or directory: './sample_path'

## torch.max
torch.max返回的是要求的最大值，而不是最大值的坐标
与广播机制

In [17]:
import torch 
a = torch.tensor([[1, 2, 3, 4], [4, 2, 3, 1]])
b = torch.tensor([[0, 5, 4, 2], [2, 3, 5, 0], [1, 3, 5, 2]])
c = torch.max(a[:, None, :2], b[:, :2])  # 需要结果是一个2×3×2的
print(a[:, None, :2])  # 2×1×2 
print(b[:, :2])  # 3×2
print(c)

tensor([[[1, 2]],

        [[4, 2]]])
tensor([[0, 5],
        [2, 3],
        [1, 3]])
tensor([[[1, 5],
         [2, 3],
         [1, 3]],

        [[4, 5],
         [4, 3],
         [4, 3]]])


In [21]:
import torch
a = torch.randn(3, 4)
b, c = torch.max(a, 0)  # torch.max(input, dim) dim: the dimension to reduce
print('a:', a)
print('b:', b)
print('c:', c)

a: tensor([[ 0.4272,  1.1686,  0.0894,  1.3237],
        [-0.1953, -0.9074,  0.8726,  0.3237],
        [ 0.5091,  0.6331,  1.0734, -0.4880]])
b: tensor([0.5091, 1.1686, 1.0734, 1.3237])
c: tensor([2, 0, 2, 0])


## torch.argmax
返回的是最大值对应的坐标

In [18]:
import torch 
a = torch.randn(4, 4)
b = torch.argmax(a, dim=0)
c = torch.argmax(a, dim=1)
print('a:', a)
print('b:', b)
print('c:', c)

a: tensor([[ 0.2551, -0.4097,  0.2170, -0.3249],
        [-0.1741, -0.8483, -0.1259,  0.4450],
        [-0.3797, -1.4070, -0.2251, -0.1578],
        [-1.3012, -0.3973,  0.7022, -1.3084]])
b: tensor([0, 3, 3, 1])
c: tensor([0, 3, 3, 2])


## torch.argsort
返回排序后的坐标

In [19]:
import torch
a = torch.randn(4, 4)
b = torch.argsort(a, dim=0)
c = torch.argsort(a, dim=1)
print('a:', a)
print('b:', b)
print('c:', c)

a: tensor([[ 0.9552,  0.7903, -3.0834, -0.6885],
        [ 1.1864,  0.7248, -2.1739,  0.6357],
        [ 1.9470,  0.8816,  0.0175,  1.7207],
        [-0.1591, -1.1799,  1.3074,  0.0632]])
b: tensor([[3, 3, 0, 0],
        [0, 1, 1, 3],
        [1, 0, 2, 1],
        [2, 2, 3, 2]])
c: tensor([[2, 3, 1, 0],
        [2, 3, 1, 0],
        [2, 1, 3, 0],
        [1, 0, 3, 2]])


## torch.clamp
过滤

In [20]:
import torch
a = torch.randn(5)
b = torch.clamp(a, min=-0.5, max=0.5)
print('a:', a)
print('b:', b)

a: tensor([-0.2850,  0.8066, -0.4880,  0.0433, -0.5219])
b: tensor([-0.2850,  0.5000, -0.4880,  0.0433, -0.5000])
