## PyTorch库的使用

### 标量对向量求导

In [1]:
import torch
x=torch.arange(4.0)#生成一个长度为4的张量
x

tensor([0., 1., 2., 3.])

In [2]:
x.requires_grad=True
x.grad

In [3]:
y=torch.dot(x,x)
y

tensor(14., grad_fn=<DotBackward0>)

In [4]:
y.backward()
x.grad

tensor([0., 2., 4., 6.])

In [5]:
#默认情况下torch会自动累计grad，因此要执行清空操作
x.grad.zero_()
y=x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

### 向量对向量的求导（深度学习不常用）

In [6]:
x.grad.zero_()
y=x*x
y.sum().backward()
x.grad

tensor([0., 2., 4., 6.])

In [7]:
x.grad.zero_()
y=x*x
u=y.detach()#之前的y=x*x，detach()后y=x*x具体的张量，不再是一个关于x的表达式
z=u*x
z.sum().backward()
x.grad

tensor([0., 1., 4., 9.])

### PyTorch库中的一些函数的用法

In [8]:
x=torch.normal(mean=0,std=1,size=(5,5))#生成一个五行五列的以0为均值，1为标准差的张量
x

tensor([[-0.2845,  0.5344,  0.6067,  1.5015, -1.3238],
        [-0.3295, -1.0833, -0.7560,  1.2955,  0.0232],
        [-0.2074, -0.5863,  0.7423, -0.1134, -0.7970],
        [ 0.7851,  0.5805, -0.2434,  1.0231, -1.2018],
        [-0.3333, -0.1922, -0.9020,  2.0084,  1.3773]])

In [9]:
w=torch.normal(0,1,(5,1))
b=1
y=torch.matmul(x,w)+b#矩阵乘法
y
y=x@w
y

tensor([[-2.1241],
        [-1.3604],
        [-0.0813],
        [ 1.2929],
        [-2.9899]])

In [10]:
print(y.reshape(-1,1))#重构为一列
print(y.reshape(1,-1))#重构为一行
print(len(y.reshape(-1,1)))
print(len(y.reshape(1,-1)))

tensor([[-2.1241],
        [-1.3604],
        [-0.0813],
        [ 1.2929],
        [-2.9899]])
tensor([[-2.1241, -1.3604, -0.0813,  1.2929, -2.9899]])
5
1


In [11]:
a=torch.tensor([[1,2,3],[4,5,6]])
print(a.sum(0,keepdim=True))
print(a.sum(1,keepdim=True))

tensor([[5, 7, 9]])
tensor([[ 6],
        [15]])


In [12]:
a=torch.tensor([[1,2,3],[4,5,6]])
print(torch.matmul(a,a.T))#做常规的矩阵乘法

tensor([[14, 32],
        [32, 77]])


In [13]:
W=torch.normal(0,0.01,size=(784,10),requires_grad=True)
print(W.shape)
print(W.shape[0])#返回的是第0维的shape

torch.Size([784, 10])
784


In [14]:
a=torch.tensor([[1,2,3],
                [3,7,1],
                [2,1,3]])
print(a.argmax(axis=1))
print(a.argmax(axis=0))

tensor([2, 1, 2])
tensor([1, 1, 0])


In [15]:
a=torch.tensor([[1,-2,3],
                [-4,5,6]])
print(torch.zeros_like(a))
print(torch.max(a,torch.zeros_like(a)))

tensor([[0, 0, 0],
        [0, 0, 0]])
tensor([[1, 0, 3],
        [0, 5, 6]])


In [16]:
import numpy as np
import torch
true_w = np.zeros(20)  # 分配大量的空间
true_w[0:4] = np.array([5, 1.2, -3.4, 5.6])
features = np.random.normal(size=(100 + 100, 1))
np.random.shuffle(features)
poly_features = np.power(features, np.arange(20).reshape(1, -1))#扩展为features行，20列数组
labels = np.dot(poly_features, true_w)
print(np.dot(poly_features, true_w).shape)

(200,)


In [17]:
a=torch.tensor([[1,2,3],
                [4,5,6]])
b=torch.tensor([[4,5,6],
               [7,8,9]])
print(torch.cat((a,b),1))
print(torch.cat((a,b),0))

tensor([[1, 2, 3, 4, 5, 6],
        [4, 5, 6, 7, 8, 9]])
tensor([[1, 2, 3],
        [4, 5, 6],
        [4, 5, 6],
        [7, 8, 9]])
