# PyTorch Notes

## torch.stack
每个tensor的size必须相同，与torch.cat的区别在于，torch.stack形成了新的维度，而torch.cat不形成新的维度

In [14]:
import torch
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])
c = torch.stack([a, b], dim=0)
d = torch.stack([a, b], dim=1)
# e = torch.tensor([[1, 2, 3], [4, 5, 6]])
# f = torch.stack([a, e], dim=1) Error:stack expects each tensor to be equal size, but got [3] at entry 0 and [2, 3] at entry 1
print('dim=0 stack:', c)
print('dim=1 stack:', d)

dim=0 stack: tensor([[1, 2, 3],
        [4, 5, 6]])
dim=1 stack: tensor([[1, 4],
        [2, 5],
        [3, 6]])


## torch.cat
在相应dim上进行扩展，别的dim的个数不变

In [11]:
import torch
a = torch.tensor([[1, 2, 3], [1, 2, 3]])
b = torch.cat((a, a), dim=0)
c = torch.cat((a, a), dim=1)
print('dim=0 cat:', b)
print('dim=1 cat:', c)

dim=0 cat: tensor([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]])
dim=1 cat: tensor([[1, 2, 3, 1, 2, 3],
        [1, 2, 3, 1, 2, 3]])


## torch.split
torch.split(tensor, split_size_or_sections, dim=0)
torch.chunk是比较简单的split

In [14]:
import torch
a = torch.randn(size=(5, 2))
print('tensor:', a)
b = torch.split(a, 2) # 在dim=0上，每两个划一个tensor
c = torch.split(a, [1, 4]) # 在dim=0上，按[1, 4]划分tensor
print('b:', b)
print('c:', c)

tensor: tensor([[-0.6045, -0.0728],
        [-0.1323, -1.2683],
        [ 1.4868,  1.6569],
        [ 1.4649,  0.2597],
        [-0.0153,  0.5289]])
b: (tensor([[-0.6045, -0.0728],
        [-0.1323, -1.2683]]), tensor([[1.4868, 1.6569],
        [1.4649, 0.2597]]), tensor([[-0.0153,  0.5289]]))
c: (tensor([[-0.6045, -0.0728]]), tensor([[-0.1323, -1.2683],
        [ 1.4868,  1.6569],
        [ 1.4649,  0.2597],
        [-0.0153,  0.5289]]))


## torch.tensor.detach
在 PyTorch 中，.detach() 方法的主要作用是将一个变量从当前的计算图中分离出来，阻止未来的计算在这个变量上的操作被记录在图中。这意味着使用 .detach() 方法的变量不会在反向传播过程中更新其梯度

## torch.meshgrid
将一组横坐标和一组纵坐标扩展后得以两两组合，相当于笛卡尔积，一般会reshape，方便后续匹配x和y

In [5]:
import torch
a = torch.tensor([1, 2, 3, 4])
b = torch.tensor([1, 2, 3])
x, y = torch.meshgrid([a, b], indexing='ij')
print('x:', x)
print('y:', y)
print('x.reshape:', x.reshape(-1))
print('y.reshape:', y.reshape(-1))

x: tensor([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3],
        [4, 4, 4]])
y: tensor([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]])
x.reshape: tensor([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4])
y.reshape: tensor([1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])


## torch.tensor.repeat

In [5]:
import torch
a = torch.tensor([1, 2, 3])
x = 5  # 行上扩展的个数
y = 2  # 列上扩展的个数
b = a.repeat(x, y)
print('b:', b)

b: tensor([[1, 2, 3, 1, 2, 3],
        [1, 2, 3, 1, 2, 3],
        [1, 2, 3, 1, 2, 3],
        [1, 2, 3, 1, 2, 3],
        [1, 2, 3, 1, 2, 3]])


## torch.repeat_interleave 
交错的重复
similar to numpy.repeat

In [13]:
import torch
a = torch.tensor([1, 2, 3])
b = a.repeat_interleave(2)
c = torch.repeat_interleave(a, 2, dim=0)
d = torch.tensor([[1, 2], [3, 4]])
e = torch.repeat_interleave(d, 2, dim=0)
f = torch.repeat_interleave(d, 2, dim=1)
print('b:', b)
print('c:', c)
print('e:', e)
print('f:', f)

b: tensor([1, 1, 2, 2, 3, 3])
c: tensor([1, 1, 2, 2, 3, 3])
e: tensor([[1, 2],
        [1, 2],
        [3, 4],
        [3, 4]])
f: tensor([[1, 1, 2, 2],
        [3, 3, 4, 4]])


## torch.unsqueeze
返回的tensor指定的维度的size为1

In [19]:
import torch
a = torch.tensor([[1, 2, 3],[4, 5, 6]])
b = torch.unsqueeze(a, dim=0)
c = torch.unsqueeze(a, dim=1)
d = torch.unsqueeze(a, dim=2)
print('b:', b)
print('c:', c)
print('d:', d)

b: tensor([[[1, 2, 3],
         [4, 5, 6]]])
c: tensor([[[1, 2, 3]],

        [[4, 5, 6]]])
d: tensor([[[1],
         [2],
         [3]],

        [[4],
         [5],
         [6]]])


## torchvision.read_image
将图片通过RGB值读入变量

In [ ]:
import torchvision
image = torchvision.io.read_image('./sample_path')

## torch.max
与广播机制

In [24]:
import torch 
a = torch.tensor([[1, 2, 3, 4], [4, 2, 3, 1]])
b = torch.tensor([[0, 5, 4, 2], [2, 3, 5, 0], [1, 3, 5, 2]])
c = torch.max(a[:, None, :2], b[:, :2])  # 需要结果是一个2×3×2的
print(a[:, None, :2])  # 2×1×2 
print(b[:, :2])  # 3×2
print(c)

tensor([[[1, 2]],

        [[4, 2]]])
tensor([[0, 5],
        [2, 3],
        [1, 3]])
tensor([[[1, 5],
         [2, 3],
         [1, 3]],

        [[4, 5],
         [4, 3],
         [4, 3]]])


## torch.clamp
过滤

In [25]:
import torch
a = torch.randn(5)
b = torch.clamp(a, min=-0.5, max=0.5)
print('a:', a)
print('b:', b)

a: tensor([-1.3437e-03, -3.8818e-01, -6.7234e-01,  2.0336e+00,  1.6577e-01])
b: tensor([-0.0013, -0.3882, -0.5000,  0.5000,  0.1658])
