## PyTorch库的使用

### 标量对向量求导

In [1]:
import torch
x=torch.arange(4.0)#生成一个长度为4的张量
x

tensor([0., 1., 2., 3.])

In [2]:
x.requires_grad=True
x.grad

In [3]:
y=torch.dot(x,x)
y

tensor(14., grad_fn=<DotBackward0>)

In [4]:
y.backward()
x.grad

tensor([0., 2., 4., 6.])

In [5]:
#默认情况下torch会自动累计grad，因此要执行清空操作
x.grad.zero_()
y=x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

### 向量对向量的求导（深度学习不常用）

In [6]:
x.grad.zero_()
y=x*x
y.sum().backward()
x.grad

tensor([0., 2., 4., 6.])

In [7]:
x.grad.zero_()
y=x*x
u=y.detach()#之前的y=x*x，detach()后y=x*x具体的张量，不再是一个关于x的表达式
z=u*x
z.sum().backward()
x.grad

tensor([0., 1., 4., 9.])

### PyTorch库中的一些函数的用法

In [8]:
x=torch.normal(mean=0,std=1,size=(5,5))#生成一个五行五列的以0为均值，1为标准差的张量
x

tensor([[-0.9038, -0.7001, -0.0991,  0.7307,  0.9716],
        [-0.2119, -0.4040, -0.1519,  0.9493, -1.0600],
        [ 0.0777,  0.3045, -0.0504, -1.2636, -1.0784],
        [-0.2508, -0.6068,  0.5360, -0.2403,  0.2041],
        [ 0.7592,  1.0419,  1.5394, -0.2941,  0.1016]])

In [13]:
w=torch.normal(0,1,(5,1))
b=1
y=torch.matmul(x,w)+b#矩阵乘法
y

tensor([[ 0.5568],
        [ 2.9298],
        [ 1.5854],
        [ 0.3361],
        [-1.1870]])

In [16]:
print(y.reshape(-1,1))#重构为一列
print(y.reshape(1,-1))#重构为一行
print(len(y.reshape(-1,1)))
print(len(y.reshape(1,-1)))

tensor([[ 0.5568],
        [ 2.9298],
        [ 1.5854],
        [ 0.3361],
        [-1.1870]])
tensor([[ 0.5568,  2.9298,  1.5854,  0.3361, -1.1870]])
5
1
